import type { CanvasViewState, Item, ItemLink, Space } from "./types";

const now = "2026-06-06T12:00:00.000Z";

export const seedSpaces: Space[] = [
  {
    id: "space-today-focus",
    name: "Today's Focus",
    icon: "target",
    sortOrder: -1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "space-mind",
    name: "Mind",
    icon: "sparkles",
    sortOrder: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "space-work",
    name: "Work",
    icon: "briefcase",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "space-reading",
    name: "Reading list",
    icon: "book",
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedItems: Item[] = [
  {
    id: "item-origin",
    spaceId: "space-mind",
    type: "thought",
    x: 90,
    y: 60,
    width: 300,
    height: 140,
    text: "Engram = my second brain. Everything lives on one infinite canvas - thoughts, todos, files, links. Nothing is trapped in a list.",
    accent: "violet",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-spatial",
    spaceId: "space-mind",
    type: "task",
    x: 450,
    y: 50,
    width: 270,
    height: 124,
    title: "Map out the spatial canvas interactions",
    accent: "gold",
    done: true,
    priority: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-capture",
    spaceId: "space-mind",
    type: "task",
    x: 450,
    y: 186,
    width: 270,
    height: 124,
    title: "Wire quick-capture to a global hotkey",
    accent: "red",
    done: true,
    priority: 1,
    dueAt: "2026-06-06T14:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-timeline",
    spaceId: "space-mind",
    type: "task",
    x: 450,
    y: 330,
    width: 270,
    height: 124,
    title: "Connect todos to the timeline view",
    accent: "gold",
    done: false,
    priority: 2,
    dueAt: "2026-06-07T10:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-note",
    spaceId: "space-mind",
    type: "thought",
    x: 155,
    y: 300,
    width: 290,
    height: 120,
    text: "Idea: hold Space + drag to pan. Double-click empty canvas to drop a thought right where you're looking.",
    accent: "violet",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-reading",
    spaceId: "space-mind",
    type: "thought",
    x: 175,
    y: 535,
    width: 280,
    height: 140,
    text: 'Reading: "Building a Second Brain". Capture -> Organize -> Distill -> Express. The canvas is for the messy middle.',
    accent: "violet",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-dentist",
    spaceId: "space-mind",
    type: "task",
    x: 475,
    y: 520,
    width: 270,
    height: 102,
    title: "Call the dentist back",
    accent: "blue",
    done: false,
    priority: 3,
    dueAt: "2026-06-06T16:30:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-planning",
    spaceId: "space-mind",
    type: "task",
    x: 520,
    y: 700,
    width: 270,
    height: 102,
    title: "Draft Q3 planning doc",
    accent: "red",
    done: false,
    priority: 1,
    dueAt: "2026-06-08T09:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-evergreen",
    spaceId: "space-mind",
    type: "link",
    x: 780,
    y: 70,
    width: 270,
    height: 180,
    title: "Andy Matuschak - Evergreen notes",
    url: "https://notes.andymatuschak.org",
    text: "Notes should be atomic and densely linked. The reference relationship is the unit of thought.",
    accent: "teal",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-image",
    spaceId: "space-mind",
    type: "image",
    x: 820,
    y: 330,
    width: 260,
    height: 290,
    title: "whiteboard-sketch.png",
    source: "whiteboard-sketch.png",
    caption: "A dropped image card placeholder.",
    accent: "teal",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-question",
    spaceId: "space-mind",
    type: "thought",
    x: 1130,
    y: 610,
    width: 300,
    height: 96,
    text: "A question worth keeping: what would this look like if it were easy?",
    accent: "violet",
    done: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-review",
    spaceId: "space-mind",
    type: "task",
    x: 1195,
    y: 220,
    width: 270,
    height: 104,
    title: "Review pull requests",
    accent: "gold",
    done: true,
    priority: 2,
    dueAt: "2026-06-06T11:00:00.000Z",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "item-groceries",
    spaceId: "space-mind",
    type: "task",
    x: 1215,
    y: 450,
    width: 270,
    height: 104,
    title: "Groceries: oat milk, eggs, coffee",
    accent: "blue",
    done: true,
    priority: 3,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedLinks: ItemLink[] = [
  {
    id: "link-origin-spatial",
    spaceId: "space-mind",
    fromItemId: "item-origin",
    toItemId: "item-spatial",
    createdAt: now,
  },
  {
    id: "link-origin-capture",
    spaceId: "space-mind",
    fromItemId: "item-origin",
    toItemId: "item-capture",
    createdAt: now,
  },
  {
    id: "link-origin-note",
    spaceId: "space-mind",
    fromItemId: "item-origin",
    toItemId: "item-note",
    createdAt: now,
  },
  {
    id: "link-reading-evergreen",
    spaceId: "space-mind",
    fromItemId: "item-reading",
    toItemId: "item-evergreen",
    createdAt: now,
  },
  {
    id: "link-evergreen-image",
    spaceId: "space-mind",
    fromItemId: "item-evergreen",
    toItemId: "item-image",
    createdAt: now,
  },
];

export const seedViewStates: CanvasViewState[] = [
  {
    id: "view-today-focus",
    spaceId: "space-today-focus",
    panX: 100,
    panY: 100,
    zoom: 1,
    gridVisible: true,
    updatedAt: now,
  },
  {
    id: "view-mind",
    spaceId: "space-mind",
    panX: 240,
    panY: 40,
    zoom: 0.95,
    gridVisible: true,
    updatedAt: now,
  },
  {
    id: "view-work",
    spaceId: "space-work",
    panX: 280,
    panY: 90,
    zoom: 1,
    gridVisible: true,
    updatedAt: now,
  },
  {
    id: "view-reading",
    spaceId: "space-reading",
    panX: 280,
    panY: 90,
    zoom: 1,
    gridVisible: true,
    updatedAt: now,
  },
];
