import {
  Archive,
  BookOpen,
  Briefcase,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  File,
  Flag,
  Image as ImageIcon,
  Info,
  Keyboard,
  LayoutDashboard,
  Link as LinkIcon,
  Minus,
  MoreHorizontal,
  Pencil,
  PanelLeft,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Sparkles,
  Square,
  Target,
  Trash2,
  X,
} from "lucide-react";

export const Icons = {
  archive: Archive,
  book: BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  clock: Clock,
  file: File,
  flag: Flag,
  image: ImageIcon,
  info: Info,
  keyboard: Keyboard,
  layout: LayoutDashboard,
  link: LinkIcon,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
  pencil: Pencil,
  panel: PanelLeft,
  plus: Plus,
  rotate: RotateCcw,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  target: Target,
  trash: Trash2,
  x: X,
};
