import {
  Archive,
  BookOpen,
  Briefcase,
  Calendar,
  Check,
  ChevronLeft,
  Circle,
  Clock,
  File,
  Flag,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  Link as LinkIcon,
  Minus,
  PanelLeft,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Sparkles,
  Square,
  Target,
} from "lucide-react";

export const Icons = {
  archive: Archive,
  book: BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  chevronLeft: ChevronLeft,
  circle: Circle,
  clock: Clock,
  file: File,
  flag: Flag,
  image: ImageIcon,
  info: Info,
  layout: LayoutDashboard,
  link: LinkIcon,
  minus: Minus,
  panel: PanelLeft,
  plus: Plus,
  rotate: RotateCcw,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  target: Target,
};
